### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by Pablohn26** [sgnh/my-passport-wireless-pro-custom-fw#1]
Could you explain what features and known problems this firmware has?

I am planning to buy this device but I do not know what could I get with this custom firmware and what features are not working here and on official firmware works.

Thanks

**Comment by sgnh** [comment]
Hi

The repository contains the official firmware. Most of the features I wanted was just a matter of enabling it as it's already there as part of [Buildroot](https://buildroot.org).

Here's a quick list of what I added:

- Wireless Time Machine support for macOS
- Transmission web client for bittorrent downloads.
- Cloud backup utilities [restic](https://github.com/restic/restic) and [b2](https://github.com/Backblaze/B2_Command_Line_Tool)
- Various commandline utilities that is missing in original firmware(vim, htop, tmux, git, python, zsh etc.)
