### ISSUE TITLE
missing kernel source linux-kernel.tgz

### ISSUE THREAD

**Issue by imbeee** [sgnh/my-passport-wireless-pro-custom-fw#3]
Hi,
It seems that this repo is missing the kernel source tar file, I wonder if it is possible to share it?

**Comment by sgnh** [comment]
The tar archives exceeds Github file limits of 100mb per file, and 1gb soft limit for the entire repo so I removed them. The official source code is available here: https://downloads.wdc.com/gpl/MyPassportWirelessPro-GPL-FW1_04_17.tgz and includes the archives.

**Comment by imbeee** [comment]
Yeah, I have just got that on WD's official site and confirmed that what I need. Thanks for your reply and have a good day. :D
